"""Add tokens_used

Revision ID: 238f823619bf
Revises: b6714ad7c999
Create Date: 2025-11-28 13:01:54.072437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238f823619bf'
down_revision: Union[str, Sequence[str], None] = 'b6714ad7c999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_reports', 'upload_timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patient_reports_id'), table_name='patient_reports', postgresql_using='prefix')
    op.create_index(op.f('ix_patient_reports_id'), 'patient_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results', postgresql_using='prefix')
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.drop_index(op.f('ix_test_results_test_name'), table_name='test_results', postgresql_using='prefix')
    op.create_index(op.f('ix_test_results_test_name'), 'test_results', ['test_name'], unique=False)
    op.alter_column('users', 'medical_history',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'current_context',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users', postgresql_using='prefix')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_id'), table_name='users', postgresql_using='prefix')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', [sa.literal_column('email NULLS FIRST')], unique=True, postgresql_using='prefix')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'current_context',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'medical_history',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_test_results_test_name'), table_name='test_results')
    op.create_index(op.f('ix_test_results_test_name'), 'test_results', [sa.literal_column('test_name NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.create_index(op.f('ix_test_results_id'), 'test_results', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_patient_reports_id'), table_name='patient_reports')
    op.create_index(op.f('ix_patient_reports_id'), 'patient_reports', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.alter_column('patient_reports', 'upload_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
